export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL'

export const LOAD_PROJECT_REQUEST = 'LOAD_PROJECT_REQUEST'
export const LOAD_PROJECT_SUCCESS = 'LOAD_PROJECT_SUCCESS'
export const LOAD_PROJECT_FAIL = 'LOAD_PROJECT_FAIL'

export const UPDATE_WORKSPACE_SETTINGS = 'UPDATE_WORKSPACE_SETTINGS'
export const UPDATE_TRANSLATION = 'UPDATE_TRANSLATION'
export const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST'
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS'
export const UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL'

export const UPDATE_RECENT_PROJECTS_REQUEST = 'UPDATE_RECENT_PROJECTS_REQUEST'
export const UPDATE_CONFIG_REQUEST = 'UPDATE_CONFIG_REQUEST'
export const UPDATE_CONFIG_SUCCESS = 'UPDATE_CONFIG_SUCCESS'
export const UPDATE_CONFIG_FAIL = 'UPDATE_CONFIG_FAIL'
