export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";

export const UPDATE_CONFIG_REQUEST = "UPDATE_CONFIG_REQUEST";

export const UPDATE_CONFIG_RECENT_PROJECTS = "UPDATE_CONFIG_RECENT_PROJECTS";

export const UPDATE_CONFIG_FAIL = "UPDATE_CONFIG_FAIL";